//! Unified interaction record — the canonical type for any interaction that
//! feeds the identity pipeline.
//!
//! Every source (chat, comms, scheduled task, research) produces an
//! `InteractionRecord`. This record then flows through:
//!   archive → event emission → graph ingestion → self-assessment
//!
//! Provider-agnostic: works identically with Claude API, Claude Code, Ollama,
//! or any future LmProvider implementation.

use chrono::{DateTime, Utc};
use pulse_system_types::llm::{Message, MessageContent, Role};
use serde::{Deserialize, Serialize};

use crate::events::{ConversationTrust, EntityEvent, InteractionSource};
use crate::session::{end_session, ArchiveMeta};
use crate::session_store::SessionData;
use crate::utils;

use std::path::{Path, PathBuf};

/// Metadata about an interaction's resource usage and health characteristics.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct InteractionMetadata {
    /// Input tokens consumed by the LLM.
    pub input_tokens: u32,
    /// Output tokens generated by the LLM.
    pub output_tokens: u32,
    /// Number of tool loop rounds.
    pub tool_rounds: u32,
    /// Duration of the interaction in seconds (if measurable).
    pub duration_secs: Option<f64>,
    /// Session key (channel:sender) if applicable.
    pub session_key: Option<String>,
    /// Number of hallucinated turns detected by the response validator.
    pub hallucination_count: u32,
    /// Number of unmatched action claims (Phase 3 validator).
    pub action_claim_count: u32,
    /// Number of circuit breaker fires.
    pub circuit_breaker_fires: u32,
}

/// A unified record of any interaction, regardless of source or provider.
///
/// This is the canonical type that flows through the entire intake pipeline:
/// archive → event emission → graph ingestion → self-assessment.
///
/// Provider-agnostic by design — contains no provider-specific fields.
/// The same InteractionRecord is produced whether the interaction was
/// handled by Claude API, Claude Code, Ollama, or any future provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InteractionRecord {
    /// Unique identifier for this interaction.
    pub id: String,
    /// Where this interaction came from.
    pub source: InteractionSource,
    /// Trust level of the interaction.
    pub trust: ConversationTrust,
    /// When the interaction started.
    pub started_at: DateTime<Utc>,
    /// When the interaction ended (None if still in progress).
    pub ended_at: Option<DateTime<Utc>>,
    /// Name of the entity that participated.
    pub entity_name: String,
    /// Brief summary of the interaction (first ~300 chars of last response).
    pub summary: String,
    /// Full message transcript.
    pub messages: Vec<Message>,
    /// Resource usage and health data.
    pub metadata: InteractionMetadata,
}

#[allow(dead_code)]
impl InteractionRecord {
    /// Build an InteractionRecord from a live chat session.
    ///
    /// This is the primary constructor for HTTP chat interactions.
    /// Trust is determined by the caller based on the request context.
    pub fn from_session(
        session: &SessionData,
        entity_name: &str,
        trust: ConversationTrust,
        input_tokens: u32,
        output_tokens: u32,
    ) -> Self {
        let summary = summarize_messages(&session.messages);
        let duration = (Utc::now() - session.created_at).num_seconds().max(0) as f64;

        Self {
            id: uuid::Uuid::new_v4().to_string(),
            source: InteractionSource::Chat {
                channel: session.channel.clone(),
            },
            trust,
            started_at: session.created_at,
            ended_at: Some(Utc::now()),
            entity_name: entity_name.to_string(),
            summary,
            messages: session.messages.clone(),
            metadata: InteractionMetadata {
                input_tokens,
                output_tokens,
                tool_rounds: 0,
                duration_secs: Some(duration),
                session_key: Some(session.key.clone()),
                hallucination_count: session.hallucination_count,
                action_claim_count: session.action_claim_count,
                circuit_breaker_fires: session.circuit_breaker_count,
            },
        }
    }

    /// Build an InteractionRecord from a peer-to-peer comms conversation.
    ///
    /// Comms messages are stored as (entity_name, text) pairs rather than
    /// full Message objects. This constructor converts them.
    pub fn from_comms(
        messages: &[(String, String)],
        local_entity: &str,
        peer_entity: &str,
        trust: ConversationTrust,
    ) -> Self {
        let converted: Vec<Message> = messages
            .iter()
            .map(|(entity, text)| {
                let role = if entity == local_entity {
                    Role::Assistant
                } else {
                    Role::User
                };
                Message {
                    role,
                    content: MessageContent::Text(text.clone()),
                    source: None,
                }
            })
            .collect();

        let summary = summarize_messages(&converted);

        Self {
            id: uuid::Uuid::new_v4().to_string(),
            source: InteractionSource::Comms {
                peer: peer_entity.to_string(),
            },
            trust,
            started_at: Utc::now(),
            ended_at: Some(Utc::now()),
            entity_name: local_entity.to_string(),
            summary,
            messages: converted,
            metadata: InteractionMetadata::default(),
        }
    }

    /// Build an InteractionRecord from a scheduled task execution.
    pub fn from_task(
        task_name: &str,
        entity_name: &str,
        messages: Vec<Message>,
        started_at: DateTime<Utc>,
        metadata: InteractionMetadata,
    ) -> Self {
        let summary = summarize_messages(&messages);

        Self {
            id: uuid::Uuid::new_v4().to_string(),
            source: InteractionSource::ScheduledTask {
                task_name: task_name.to_string(),
            },
            trust: ConversationTrust::Owner,
            started_at,
            ended_at: Some(Utc::now()),
            entity_name: entity_name.to_string(),
            summary,
            messages,
            metadata,
        }
    }

    /// Build an InteractionRecord from a research intent execution.
    pub fn from_research(
        topic: &str,
        entity_name: &str,
        messages: Vec<Message>,
        started_at: DateTime<Utc>,
        metadata: InteractionMetadata,
    ) -> Self {
        let summary = summarize_messages(&messages);

        Self {
            id: uuid::Uuid::new_v4().to_string(),
            source: InteractionSource::Research {
                topic: topic.to_string(),
            },
            trust: ConversationTrust::Owner,
            started_at,
            ended_at: Some(Utc::now()),
            entity_name: entity_name.to_string(),
            summary,
            messages,
            metadata,
        }
    }

    /// Produce a PostInteraction event from this record.
    ///
    /// Used to emit onto the event bus after an interaction completes.
    pub fn to_event(&self) -> EntityEvent {
        EntityEvent::PostInteraction {
            source: self.source.clone(),
            trust: self.trust.clone(),
            summary: self.summary.clone(),
            input_tokens: self.metadata.input_tokens,
            output_tokens: self.metadata.output_tokens,
        }
    }

    /// Produce archive metadata from this record.
    pub fn to_archive_meta(&self) -> ArchiveMeta {
        let trigger = match &self.source {
            InteractionSource::Chat { .. } => "session-end".to_string(),
            InteractionSource::Comms { peer } => format!("comms-end-{}", peer),
            InteractionSource::ScheduledTask { task_name } => {
                format!("task-end-{}", task_name)
            }
            InteractionSource::Research { topic } => format!("research-end-{}", topic),
        };

        let channel = match &self.source {
            InteractionSource::Chat { channel } => channel.clone(),
            InteractionSource::Comms { .. } => "comms".to_string(),
            InteractionSource::ScheduledTask { task_name } => {
                format!("task:{}", task_name)
            }
            InteractionSource::Research { topic } => format!("research:{}", topic),
        };

        ArchiveMeta {
            trigger,
            channel,
            entity_name: self.entity_name.clone(),
            session_key: self.metadata.session_key.clone(),
        }
    }

    /// Archive this interaction — writes the conversation to disk, updates
    /// EPHEMERAL.md, and logs to LOGBOOK.md.
    ///
    /// Returns the archive path on success (for graph ingestion).
    pub fn archive(&self, root_dir: &Path) -> Option<PathBuf> {
        if self.messages.is_empty() {
            return None;
        }

        end_session(
            root_dir,
            &self.entity_name,
            &self.messages,
            &self.to_archive_meta().channel,
            &self.to_archive_meta().trigger,
            self.metadata.session_key.as_deref(),
        )
    }

    /// Source label for display (logs, assessments, etc.).
    pub fn source_label(&self) -> String {
        match &self.source {
            InteractionSource::Chat { channel } => format!("chat:{}", channel),
            InteractionSource::Comms { peer } => format!("comms:{}", peer),
            InteractionSource::ScheduledTask { task_name } => format!("task:{}", task_name),
            InteractionSource::Research { topic } => format!("research:{}", topic),
        }
    }

    /// Trust label for display.
    pub fn trust_label(&self) -> &'static str {
        match &self.trust {
            ConversationTrust::Owner => "owner",
            ConversationTrust::LocalPeer => "local-peer",
            ConversationTrust::RemotePeer => "remote-peer",
            ConversationTrust::Public => "public",
        }
    }

    /// Whether this interaction is significant enough to warrant a
    /// self-assessment. Filters out trivial health checks and empty exchanges.
    pub fn is_assessable(&self) -> bool {
        let has_content = self.metadata.input_tokens + self.metadata.output_tokens > 100;
        let has_messages = self.messages.len() >= 2;
        has_content || has_messages
    }
}

/// Extract a summary from the last assistant message in a conversation.
/// Truncates to ~300 chars.
fn summarize_messages(messages: &[Message]) -> String {
    let last_assistant = messages
        .iter()
        .rev()
        .find(|m| matches!(m.role, Role::Assistant));

    let text = match last_assistant {
        Some(msg) => match &msg.content {
            MessageContent::Text(t) => t.clone(),
            MessageContent::Blocks(blocks) => blocks
                .iter()
                .filter_map(|b| match b {
                    pulse_system_types::llm::ContentBlock::Text { text } => Some(text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join(" "),
        },
        None => String::new(),
    };

    if text.len() > utils::SUMMARY_TRUNCATE_LEN {
        format!(
            "{}...",
            utils::safe_truncate(&text, utils::SUMMARY_TRUNCATE_LEN)
        )
    } else {
        text
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::events::{ConversationTrust, InteractionSource};
    use pulse_system_types::llm::{Message, MessageContent, Role};

    fn make_messages(count: usize) -> Vec<Message> {
        let mut msgs = Vec::new();
        for i in 0..count {
            let role = if i % 2 == 0 {
                Role::User
            } else {
                Role::Assistant
            };
            msgs.push(Message {
                role,
                content: MessageContent::Text(format!("message {}", i)),
                source: None,
            });
        }
        msgs
    }

    #[test]
    fn from_task_produces_correct_source() {
        let meta = InteractionMetadata {
            input_tokens: 100,
            output_tokens: 200,
            ..Default::default()
        };
        let record = InteractionRecord::from_task(
            "morning_orientation",
            "Echo",
            make_messages(4),
            Utc::now(),
            meta,
        );

        assert!(matches!(
            record.source,
            InteractionSource::ScheduledTask { ref task_name } if task_name == "morning_orientation"
        ));
        assert!(matches!(record.trust, ConversationTrust::Owner));
        assert_eq!(record.metadata.input_tokens, 100);
        assert_eq!(record.metadata.output_tokens, 200);
        assert_eq!(record.entity_name, "Echo");
    }

    #[test]
    fn from_research_produces_correct_source() {
        let meta = InteractionMetadata {
            input_tokens: 50,
            output_tokens: 150,
            ..Default::default()
        };
        let record = InteractionRecord::from_research(
            "emergence",
            "Echo",
            make_messages(2),
            Utc::now(),
            meta,
        );

        assert!(matches!(
            record.source,
            InteractionSource::Research { ref topic } if topic == "emergence"
        ));
    }

    #[test]
    fn from_comms_converts_messages_correctly() {
        let messages = vec![
            ("Nova".to_string(), "Hello Echo".to_string()),
            ("Echo".to_string(), "Hey Nova".to_string()),
        ];
        let record =
            InteractionRecord::from_comms(&messages, "Echo", "Nova", ConversationTrust::LocalPeer);

        assert!(matches!(
            record.source,
            InteractionSource::Comms { ref peer } if peer == "Nova"
        ));
        assert!(matches!(record.trust, ConversationTrust::LocalPeer));
        assert_eq!(record.messages.len(), 2);
        // Nova's message should be Role::User (not local entity)
        assert!(matches!(record.messages[0].role, Role::User));
        // Echo's message should be Role::Assistant (local entity)
        assert!(matches!(record.messages[1].role, Role::Assistant));
    }

    #[test]
    fn to_event_preserves_source_and_trust() {
        let meta = InteractionMetadata {
            input_tokens: 50,
            output_tokens: 150,
            ..Default::default()
        };
        let record = InteractionRecord::from_research(
            "emergence",
            "Echo",
            make_messages(2),
            Utc::now(),
            meta,
        );

        let event = record.to_event();
        match event {
            EntityEvent::PostInteraction {
                source,
                trust,
                input_tokens,
                output_tokens,
                ..
            } => {
                assert!(
                    matches!(source, InteractionSource::Research { ref topic } if topic == "emergence")
                );
                assert!(matches!(trust, ConversationTrust::Owner));
                assert_eq!(input_tokens, 50);
                assert_eq!(output_tokens, 150);
            }
            _ => panic!("Expected PostInteraction event"),
        }
    }

    #[test]
    fn to_archive_meta_generates_correct_triggers() {
        let chat_record = InteractionRecord {
            id: "test".into(),
            source: InteractionSource::Chat {
                channel: "discord".into(),
            },
            trust: ConversationTrust::Owner,
            started_at: Utc::now(),
            ended_at: None,
            entity_name: "Echo".into(),
            summary: String::new(),
            messages: vec![],
            metadata: InteractionMetadata::default(),
        };
        let meta = chat_record.to_archive_meta();
        assert_eq!(meta.trigger, "session-end");
        assert_eq!(meta.channel, "discord");

        let comms_record = InteractionRecord {
            source: InteractionSource::Comms {
                peer: "Nova".into(),
            },
            trust: ConversationTrust::LocalPeer,
            ..chat_record.clone()
        };
        let meta = comms_record.to_archive_meta();
        assert_eq!(meta.trigger, "comms-end-Nova");
        assert_eq!(meta.channel, "comms");

        let task_record = InteractionRecord {
            source: InteractionSource::ScheduledTask {
                task_name: "reflection".into(),
            },
            ..chat_record
        };
        let meta = task_record.to_archive_meta();
        assert_eq!(meta.trigger, "task-end-reflection");
        assert_eq!(meta.channel, "task:reflection");
    }

    #[test]
    fn is_assessable_filters_trivial() {
        let trivial = InteractionRecord {
            id: "test".into(),
            source: InteractionSource::Chat {
                channel: "health".into(),
            },
            trust: ConversationTrust::Owner,
            started_at: Utc::now(),
            ended_at: None,
            entity_name: "Echo".into(),
            summary: String::new(),
            messages: vec![Message {
                role: Role::Assistant,
                content: MessageContent::Text("ok".into()),
                source: None,
            }],
            metadata: InteractionMetadata {
                input_tokens: 10,
                output_tokens: 5,
                ..Default::default()
            },
        };
        assert!(!trivial.is_assessable());

        let substantial = InteractionRecord {
            messages: make_messages(4),
            metadata: InteractionMetadata {
                input_tokens: 500,
                output_tokens: 300,
                ..Default::default()
            },
            ..trivial
        };
        assert!(substantial.is_assessable());
    }

    #[test]
    fn source_label_formats_correctly() {
        let record = InteractionRecord {
            id: "test".into(),
            source: InteractionSource::Chat {
                channel: "discord".into(),
            },
            trust: ConversationTrust::Owner,
            started_at: Utc::now(),
            ended_at: None,
            entity_name: "Echo".into(),
            summary: String::new(),
            messages: vec![],
            metadata: InteractionMetadata::default(),
        };
        assert_eq!(record.source_label(), "chat:discord");
    }

    #[test]
    fn trust_label_returns_correct_strings() {
        let mut record = InteractionRecord {
            id: "test".into(),
            source: InteractionSource::Chat {
                channel: "test".into(),
            },
            trust: ConversationTrust::Owner,
            started_at: Utc::now(),
            ended_at: None,
            entity_name: "Echo".into(),
            summary: String::new(),
            messages: vec![],
            metadata: InteractionMetadata::default(),
        };

        assert_eq!(record.trust_label(), "owner");
        record.trust = ConversationTrust::LocalPeer;
        assert_eq!(record.trust_label(), "local-peer");
        record.trust = ConversationTrust::RemotePeer;
        assert_eq!(record.trust_label(), "remote-peer");
        record.trust = ConversationTrust::Public;
        assert_eq!(record.trust_label(), "public");
    }

    #[test]
    fn summarize_messages_uses_last_assistant() {
        let messages = vec![
            Message {
                role: Role::User,
                content: MessageContent::Text("question".into()),
                source: None,
            },
            Message {
                role: Role::Assistant,
                content: MessageContent::Text("first answer".into()),
                source: None,
            },
            Message {
                role: Role::User,
                content: MessageContent::Text("follow up".into()),
                source: None,
            },
            Message {
                role: Role::Assistant,
                content: MessageContent::Text("second answer".into()),
                source: None,
            },
        ];
        let summary = summarize_messages(&messages);
        assert_eq!(summary, "second answer");
    }

    #[test]
    fn summarize_truncates_long_messages() {
        let long_text = "x".repeat(500);
        let messages = vec![Message {
            role: Role::Assistant,
            content: MessageContent::Text(long_text),
            source: None,
        }];
        let summary = summarize_messages(&messages);
        assert!(summary.len() < 400);
        assert!(summary.ends_with("..."));
    }

    #[test]
    fn summarize_empty_returns_empty() {
        let summary = summarize_messages(&[]);
        assert!(summary.is_empty());
    }
}
